# NUMPY 

17/07


###  Creating an array

1) Create an array from a list

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. Create an array from a tuple

In [5]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


3) Create an array from a set

In [8]:
import numpy as np
arr = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


4) Create a 0-dimensional array and display data type and array

In [12]:
import numpy as np
arr = np.array(49)
print(arr)
print(arr.ndim)

49
0


5) Create a 1-dimensional array and display data type and array

In [13]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)

[1 2 3]
1


6) Create a 2-dimensional array and display data type and array

In [15]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


19/07

### Accessing an array

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])  #1-d array
print(arr[0])
print(arr[-2])


1
4


In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2-d array
print(arr[0, 1])
print(arr[1, -1])
print(arr[2, 2])

2
6
9


### Slicing an array

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:3])
print(arr[-4:-2])
print(arr[::2])
print(arr[::])
print(arr[2:])
print(arr[:3])


[2 3]
[2 3]
[1 3 5]
[1 2 3 4 5]
[3 4 5]
[1 2 3]
