# NUMPY 

In [1]:
import numpy as np

17/07


###  Creating an array

1) Create an array from a list

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. Create an array from a tuple

In [ ]:

arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


3) Create an array from a set

In [ ]:

arr = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


4) Create a 0-dimensional array and display data type and array

In [ ]:
arr = np.array(49)
print(arr)
print(arr.ndim)

49
0


5) Create a 1-dimensional array and display data type and array

In [ ]:
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)

[1 2 3]
1


6) Create a 2-dimensional array and display data type and array

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print(arr.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

19/07

### Accessing an array

In [ ]:

arr = np.array([1, 2, 3, 4, 5])  #1-d array
print(arr[0])
print(arr[-2])


1
4


In [ ]:

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])  # 2-d array
print(arr[0, 1])
print(arr[1, -1])
print(arr[2, 2])

2
6
9


### Slicing an 1d array

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:3])
print(arr[-4:-2])
print(arr[::2])
print(arr[::])
print(arr[2:])
print(arr[:3])


[2 3]
[2 3]
[1 3 5]
[1 2 3 4 5]
[3 4 5]
[1 2 3]


### Slicing and 2d array

In [ ]:

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,0:3])
print(arr[0:2,2])


[6 7 8]
[3 8]
8


In [1]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0, 1:4])
print(arr[1, 1:-1])
#print(arr[0, 1:-1])
print(arr[0, :])
#print(arr[1, :])
print(arr[0:2, 2])
print(arr[0:2, 2:4])


[7 8 9]
[2 3 4]
[7 8 9]
[1 2 3 4 5]
[3 8]
[[3 4]
 [8 9]]


### Checking data types

In [ ]:

arr = np.array([1.1, 2.2, 3.3, 4.4])
print(arr.dtype)

float64


In [ ]:

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [ ]:

arr = np.array([1,2,3,4,5],dtype='f')
print(arr.dtype)

float32


In [35]:
arr = np.array([1,4,3,44,555],dtype='S')
print(arr.dtype)
print(arr)

|S3
[b'1' b'4' b'3' b'44' b'555']


In [36]:
arr = np.array(['a','bb','c'])
print(arr.dtype)

<U2


### Copy and view in an array


In [ ]:
arr = np.array([1,2,3,4])

x = arr.copy()   # makeing a copy to a new array
x[0] = 0

print("The value of arr : ",arr)  #output the original array
print("The value of x : ",x)   # output is changed 

The value of arr :  [1 2 3 4]
The value of x :  [0 2 3 4]


In [ ]:
arr = np.array([1,2,3,4])

x = arr.view()    # view, it is a view of the original array
x[0] = 0

print("The value of arr : ",arr)  #ouput  the original array
print("The value of x : ",x)   # output is not changed

The value of arr :  [0 2 3 4]
The value of x :  [0 2 3 4]


### Displaying the shape of the array

In [ ]:
arr = np.array([10,6,7])  #is a 1d array
print(arr.shape)  #gives the shape of the array

(3,)


In [ ]:
arr = np.array([[1,3,5,7],[3,3,4,5]])  #is a 2d array
print(arr.shape)  #gives the shape of the array

(2, 4)


In [ ]:
arr = np.array([
                [[1,2],[4,5]],
                [[6,7],[8,9]]
                        ])   #is a 3d array
print(arr.shape)   #gives the shape of the array

(2, 2, 2)


### Flatten and Ravel

In [ ]:
####   ravel()                                      flatten()     ###
# --------------------------------------------------------------- ###
# 1. Returns only the reference            1. Return copy of the 
#    /view of the original array              initial array

# 2. The changes will be reflected         2. The changes done in new array
#    in both original and coped arrays        will not be reflected in original

# 3. Fasterthan flatten(), since it        3. Slower than ravel(). Since, it 
#    wont take up the memory. Simply          occupies memory.
#    refer the original only


In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])
print(arr)

newarr=arr.flatten('C')
print(newarr)

newarr=arr.flatten('f')
print(newarr)
newarr[0] = 0
print("after changes have made")
print("new arr : ",newarr)
print("og arr : ",arr[:,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
after changes have made
new arr :  [ 0  5  9  2  6 10  3  7 11  4  8 12]
og arr :  [1 5 9]


In [19]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])
print(arr)

newarr=arr.ravel('C')
print(newarr)

newarr=arr.ravel('f')
print(newarr)
newarr[0] = 0
print("after changes have made")
print("new arr : ",newarr)
print("og arr : ",arr[:,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
after changes have made
new arr :  [ 0  5  9  2  6 10  3  7 11  4  8 12]
og arr :  [1 5 9]


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print("Original array:\n", a)

# ravel() - may return a view
r = a.ravel()

# flatten() - always returns a copy
f = a.flatten('f')

# Modifying r may change 'a' if it's a view
r[0] = 100


print("Og array after the changes:\n", a)
print("ravel result:\n", r)
print("flatten result:\n", f)


Original array:
 [[1 2]
 [3 4]]
Og array after the changes:
 [[100   2]
 [  3   4]]
ravel result:
 [100   2   3   4]
flatten result:
 [200   3   2   4]


### Arrange

In [8]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print("Original array:\n", a)

# flatten() - always returns a copy
f = a.flatten('f')

f[0] = 200
print(a)
print("flatten result:\n", f)

Original array:
 [[1 2]
 [3 4]]
[[1 2]
 [3 4]]
flatten result:
 [200   3   2   4]


In [51]:
# arr = np.arange(4,10)
arr = np.arange(4,10,2)

print(arr)

[4 6 8]


In [53]:
arr = np.arange(2,14).reshape(6,2)
print(arr)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


### Iteration of arrays

##### Iterating an 1-d array

In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

for x in arr:
    print(x)

[ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


#### Iterating an 2-d array

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,6)
print(arr)

for x in arr:
    for y in x:
        print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4) # Index positions of 4 will be displayed
print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
#using concatenate()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [59]:
#using stack()

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [58]:
#using stack()

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### Spliting of array

In [64]:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = np.array_split(arr, 3)
print("Spilited into 3 :",newarr)
newarr = np.array_split(arr, 2)
print("Spilited into 4 :",newarr)


Spilited into 3 : [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
Spilited into 4 : [array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]


In [22]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


### Searching in an array

In [67]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x[0])

[3 5 6]


In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
#arr = np.array([[3, 2, 4], [5, 0, 1]])
x = np.where(arr%2 == 0) 
print(x[0])

[1 3 5 7]


In [72]:

arr = np.array([16, 70,4, 8, 9])
x = np.searchsorted(arr, 70)  # performs a binary search in the array, and returns the index
print(x)

5


### Sorting array

In [25]:
#sorting an 1d array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [27]:
#sorting an 2d array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### other programs

In [73]:
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [74]:
# Array of zeros
import numpy as np
zeors_array = np.zeros( (2, 3))  # Array of zeros as float values
print(zeors_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [75]:
# Array of zeros
import numpy as np
# Array of zeros as integer values
zeors_array = np.zeros( (2, 3), dtype = int )
print(zeors_array)

[[0 0 0]
 [0 0 0]]


In [76]:

# Array of ones
ones_array = np.ones( (1, 5), dtype=np.int32 ) # specifying dtype
print(ones_array)      # Output: [[1 1 1 1 1]]

[[1 1 1 1 1]]


#### matrix operations


In [77]:
# Matrix addition
import numpy as np
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # adding 2 matrices
print(C)

[[11  1]
 [ 8  0]]


In [78]:
# Matrix multiplication using dot()
import numpy as np
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


In [79]:
# Matrix multiplication using *
import numpy as np
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A * B      # adding 2 matrices
print(C)

[[ 18 -12]
 [ 15 -36]]


In [80]:
# Transpose of a Matrix using transpose()
import numpy as np
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


In [81]:

# Identity matrix
import numpy as np
dimension = int(input("Enter the dimension of identitiy matrix: "))
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [82]:
# create an array with zero above the main diagonal
import numpy as np
# To create an array with zero above the main diagonal
# forming a lower triangular matrix, use the numpy.tri() method in Python Numpy
# The 1st parameter is the number of rows in the array
# The 2nd parameter is the number of columns in the array
arr = np.tri(4, 4,dtype = int)
# Displaying our array
print("Array...",arr)

Array... [[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


In [83]:

# Caculating no.of elements in an array
import numpy as np
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.size) # Display no.of elements
print(A.ndim)  # Display the dimension
print(A.shape) # Display the shape of an array

6
2
(3, 2)


In [86]:

# To create an array with zero below the main diagonal
import numpy as np
arr = np.arange(25).reshape(5,5)
print(np.tril(arr))


[[ 0  0  0  0  0]
 [ 5  6  0  0  0]
 [10 11 12  0  0]
 [15 16 17 18  0]
 [20 21 22 23 24]]


In [87]:
# To create an array with zero below the main diagonal
import numpy as np
arr = np.arange(25).reshape(5,5)
print(np.tril(arr,k = -2))

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [10  0  0  0  0]
 [15 16  0  0  0]
 [20 21 22  0  0]]


In [88]:
# To create an array with zero below the main diagonal
import numpy as np
arr = np.arange(25).reshape(5,5)
print(np.tril(arr,k = -1))

[[ 0  0  0  0  0]
 [ 5  0  0  0  0]
 [10 11  0  0  0]
 [15 16 17  0  0]
 [20 21 22 23  0]]


In [89]:
# To create an array with zero above the main diagonal using tril()
import numpy as np
arr = np.arange(25).reshape(5,5)
print(np.tril(arr,k = 1))

[[ 0  1  0  0  0]
 [ 5  6  7  0  0]
 [10 11 12 13  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]
