# NUMPY 

In [1]:
import numpy as np

17/07


###  Creating an array

1) Create an array from a list

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. Create an array from a tuple

In [ ]:

arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


3) Create an array from a set

In [ ]:

arr = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


4) Create a 0-dimensional array and display data type and array

In [ ]:
arr = np.array(49)
print(arr)
print(arr.ndim)

49
0


5) Create a 1-dimensional array and display data type and array

In [ ]:
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)

[1 2 3]
1


6) Create a 2-dimensional array and display data type and array

In [ ]:

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


19/07

### Accessing an array

In [ ]:

arr = np.array([1, 2, 3, 4, 5])  #1-d array
print(arr[0])
print(arr[-2])


1
4


In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2-d array
print(arr[0, 1])
print(arr[1, -1])
print(arr[2, 2])

2
6
9


### Slicing an 1d array

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:3])
print(arr[-4:-2])
print(arr[::2])
print(arr[::])
print(arr[2:])
print(arr[:3])


[2 3]
[2 3]
[1 3 5]
[1 2 3 4 5]
[3 4 5]
[1 2 3]


### Slicing and 2d array

In [ ]:

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,3])
print(arr[0:2,2])
print(arr[1,2])

9
[3 8]
8


### Checking data types

In [ ]:

arr = np.array([1.1, 2.2, 3.3, 4.4])
print(arr.dtype)

float64


In [ ]:

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [ ]:

arr = np.array([1,2,3,4,5],dtype='f')
print(arr.dtype)

float32


In [ ]:
arr = np.array([1,4,3,4,5],dtype='S')
print(arr.dtype)
print(arr)

|S2
[b'1' b'4' b'3' b'44' b'55']


In [ ]:
arr = np.array(['y gg'])
print(arr.dtype)

<U4


### Copy and view in an array


In [16]:
arr = np.array([1,2,3,4])

x = arr.copy()   # makeing a copy to a new array
arr[0] = 0

print("The value of arr : ",arr)  #output the original array
print("The value of x : ",x)   # output is changed 

The value of arr :  [0 2 3 4]
The value of x :  [1 2 3 4]


In [15]:
arr = np.array([1,2,3,4])

x = arr.view()    # view, it is a view of the original array
arr[0] = 0

print("The value of arr : ",arr)  #ouput  the original array
print("The value of x : ",x)   # output is not changed

The value of arr :  [0 2 3 4]
The value of x :  [0 2 3 4]


### Displaying the shape of the array

In [ ]:
arr = np.array([10,6,7])  #is a 1d array
print(arr.shape)  #gives the shape of the array

(3,)


In [ ]:
arr = np.array([[1,3,5,7],
                [3,3,4,5]])  #is a 2d array
print(arr.shape)  #gives the shape of the array

(2, 4)


In [ ]:
arr = np.array([
                [[1,2,0],[4,5,0]],
                [[6,7,0],[8,9,0]],
                [[6,7,0],[8,9,0]],
                [[6,7,0],[8,9,0]]
                       ])   #is a 3d array
print(arr.shape)   #gives the shape of the array

(4, 2, 3)


### Reshaping the array using reshape(), flatten(), ravel()

#### 1-d to 2-d conversion

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 2-d to 1-d conversion

In [ ]:
arr = np.array([[1,3,5,7],
                [3,3,4,5]])
x = -2
newarr1 = arr.reshape(1,8)
newarr = arr.reshape(x) 

print(newarr1.shape)
print(newarr.shape)

print(x)

(1, 8)
(8,)
-2


In [42]:
import numpy as np
print(np.__version__)
print(np.__name__)


1.23.5
numpy


In [ ]:
arr = np.array([
                [[1,2,0],[4,5,0]],
                [[6,7,0],[8,9,0]],
                [[6,7,0],[8,9,0]],
                [[6,7,0],[8,9,0]]
                       ])  

arr2 = arr.reshape(-1)
print(arr2)


[1 2 0 4 5 0 6 7 0 8 9 0 6 7 0 8 9 0 6 7 0 8 9 0]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

