# NUMPY 

In [1]:
import numpy as np

17/07


###  Creating an array

1) Create an array from a list

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. Create an array from a tuple

In [ ]:

arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


3) Create an array from a set

In [ ]:

arr = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


4) Create a 0-dimensional array and display data type and array

In [ ]:
arr = np.array(49)
print(arr)
print(arr.ndim)

49
0


5) Create a 1-dimensional array and display data type and array

In [ ]:
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)

[1 2 3]
1


6) Create a 2-dimensional array and display data type and array

In [ ]:

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


19/07

### Accessing an array

In [ ]:

arr = np.array([1, 2, 3, 4, 5])  #1-d array
print(arr[0])
print(arr[-2])


1
4


In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2-d array
print(arr[0, 1])
print(arr[1, -1])
print(arr[2, 2])

2
6
9


### Slicing an 1d array

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:3])
print(arr[-4:-2])
print(arr[::2])
print(arr[::])
print(arr[2:])
print(arr[:3])


[2 3]
[2 3]
[1 3 5]
[1 2 3 4 5]
[3 4 5]
[1 2 3]


### Slicing and 2d array

In [ ]:

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,3])
print(arr[0:2,2])
print(arr[1,2])

9
[3 8]
8


### Checking data types

In [ ]:

arr = np.array([1.1, 2.2, 3.3, 4.4])
print(arr.dtype)

float64


In [ ]:

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [ ]:

arr = np.array([1,2,3,4,5],dtype='f')
print(arr.dtype)

float32


In [ ]:
arr = np.array([1,4,3,4,5],dtype='S')
print(arr.dtype)
print(arr)

|S2
[b'1' b'4' b'3' b'44' b'55']


In [ ]:
arr = np.array(['y gg'])
print(arr.dtype)

<U4


### Copy and view in an array


In [ ]:
arr = np.array([1,2,3,4])

x = arr.copy()   # makeing a copy to a new array
x[0] = 0

print("The value of arr : ",arr)  #output the original array
print("The value of x : ",x)   # output is changed 

The value of arr :  [1 2 3 4]
The value of x :  [0 2 3 4]


In [ ]:
arr = np.array([1,2,3,4])

x = arr.view()    # view, it is a view of the original array
x[0] = 0

print("The value of arr : ",arr)  #ouput  the original array
print("The value of x : ",x)   # output is not changed

The value of arr :  [0 2 3 4]
The value of x :  [0 2 3 4]


### Displaying the shape of the array

In [ ]:
arr = np.array([10,6,7])  #is a 1d array
print(arr.shape)  #gives the shape of the array

(3,)


In [ ]:
arr = np.array([[1,3,5,7],[3,3,4,5]])  #is a 2d array
print(arr.shape)  #gives the shape of the array

(2, 4)


In [ ]:
arr = np.array([
                [[1,2],
                 [4,5]]
                        ])   #is a 3d array
print(arr.shape)   #gives the shape of the array

(1, 2, 2)


In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])
print(arr)

newarr=arr.flatten('C')
print(newarr)

newarr=arr.flatten('f')
print(newarr)
newarr[0] = 0
print("after changes have made")
print("new arr : ",newarr)
print("og arr : ",arr[:,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
after changes have made
new arr :  [ 0  5  9  2  6 10  3  7 11  4  8 12]
og arr :  [1 5 9]


In [19]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])
print(arr)

newarr=arr.ravel('C')
print(newarr)

newarr=arr.ravel('f')
print(newarr)
newarr[0] = 0
print("after changes have made")
print("new arr : ",newarr)
print("og arr : ",arr[:,0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  5  9  2  6 10  3  7 11  4  8 12]
after changes have made
new arr :  [ 0  5  9  2  6 10  3  7 11  4  8 12]
og arr :  [1 5 9]


In [25]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print("Original array:\n", a)

# ravel() - may return a view
r = a.ravel()

# flatten() - always returns a copy
f = a.flatten()

# Modifying r may change 'a' if it's a view
r[0] = 100

print("Og array after the changes:\n", a)
print("ravel result:\n", r)
print("flatten result:\n", f)


Original array:
 [[1 2]
 [3 4]]
Og array after the changes:
 [[100   2]
 [  3   4]]
ravel result:
 [100   2   3   4]
flatten result:
 [1 2 3 4]
